name: Code format checker

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip_cache
      - name: Install formatting tools
        run: pip install black flake8

      - name: Running black
        run: black --check tibber

      - name: Running flake8
        run: flake8 --per-file-ignores="./tibber/__init__.py:E402"
